### ISSUE TITLE
Create the "What I ate Today" Page

### ISSUE THREAD

**Issue by tjm165** [509maddy/Senior-Capstone#11]
- [x] Query everything I ate on a specific date

- [x] Table of contents everything I ate today

- [x] Table renders on change

**Comment by 509maddy** [comment]
Imma comment: check out the current FoodViewController page for starters, I think it ticks all the boxes in terms of basic querying, but might need improvement and/or clean-up. I modified this file a bit in my branch when writing the back end functions as an FYI.
