### ISSUE TITLE
Today's Food Cosmetics

### ISSUE THREAD

**Issue by tjm165** [509maddy/Senior-Capstone#51]
Table
- [x] Responsive screen size
      - ensure it's scrollable if you add so many food items 

Individual Food Item Screen
- [x] If a serving equals 0 then hide it from the screen
- [x] Responsive screen size
- [x] Center everything
- [x] Make sure the order of the food groups is consistent
- [x] The name of the food should look like a page heading

**Comment by allydinhofer** [comment]
might need to get a way for it to not look ugly when it has a few food items
